spring.application.name=web
server.port=8080
management.endpoints.web.exposure.include=health,info
info.app.name=${spring.application.name}
info.app.version=1.0
info.app.description=APJ Storefront REST API
springdoc.swagger-ui.path=/docs
springdoc.api-docs.title=APJ Storefront API
springdoc.api-docs.description=REST API for managing Card resources

spring.profiles.active=dev